//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWinAdministracion.WSTerminalRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTerminalRef.WSTerminalSoap")]
    public interface WSTerminalSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar_Compania", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Companias Buscar_Compania(string pNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Compania", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Alta_Compania(AppWinAdministracion.WSTerminalRef.Companias unaCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Compania", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Eliminar_Compania(AppWinAdministracion.WSTerminalRef.Companias unaCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar_Compania", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Modificar_Compania(AppWinAdministracion.WSTerminalRef.Companias unaCompania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Companias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Companias[] Listar_Companias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Todos_Companias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Companias[] Listar_Todos_Companias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar_Terminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Terminales Buscar_Terminal(string pCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Terminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Alta_Terminal(AppWinAdministracion.WSTerminalRef.Terminales unaTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Terminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Eliminar_Terminal(AppWinAdministracion.WSTerminalRef.Terminales unaTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar_Terminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Modificar_Terminal(AppWinAdministracion.WSTerminalRef.Terminales unaTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Terminales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Terminales[] Listar_Terminales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Todos_Terminales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Terminales[] Listar_Todos_Terminales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar_Viaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Viajes Buscar_Viaje(int pCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Viaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Alta_Viaje(AppWinAdministracion.WSTerminalRef.Viajes unViaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Viaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Eliminar_Viaje(AppWinAdministracion.WSTerminalRef.Viajes unViaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar_Viaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Modificar_Viaje(AppWinAdministracion.WSTerminalRef.Viajes unViaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Viajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Viajes[] Listar_Viajes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Empleados Login(string pCed, string pPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Empleados Buscar_Empleado(string pCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTodos_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppWinAdministracion.WSTerminalRef.Empleados BuscarTodos_Empleado(string pCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Alta_Empleado(AppWinAdministracion.WSTerminalRef.Empleados unEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Eliminar_Empleado(AppWinAdministracion.WSTerminalRef.Empleados unEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Modificar_Empleado(AppWinAdministracion.WSTerminalRef.Empleados unEmpleado);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Companias : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cedulaField;
        
        private string passField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
                this.RaisePropertyChanged("Cedula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("Pass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Viajes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numeroField;
        
        private Companias companiaField;
        
        private Terminales terminalField;
        
        private System.DateTime fecha_partidaField;
        
        private System.DateTime fecha_arriboField;
        
        private int asientosField;
        
        private Empleados empleadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Companias Compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
                this.RaisePropertyChanged("Compania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Terminales Terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
                this.RaisePropertyChanged("Terminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha_partida {
            get {
                return this.fecha_partidaField;
            }
            set {
                this.fecha_partidaField = value;
                this.RaisePropertyChanged("Fecha_partida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fecha_arribo {
            get {
                return this.fecha_arriboField;
            }
            set {
                this.fecha_arriboField = value;
                this.RaisePropertyChanged("Fecha_arribo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Asientos {
            get {
                return this.asientosField;
            }
            set {
                this.asientosField = value;
                this.RaisePropertyChanged("Asientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Empleados Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("Empleado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Terminales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string ciudadField;
        
        private string paisField;
        
        private Facilidades[] listaFacilidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("Ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("Pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Facilidades[] ListaFacilidades {
            get {
                return this.listaFacilidadesField;
            }
            set {
                this.listaFacilidadesField = value;
                this.RaisePropertyChanged("ListaFacilidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Facilidades : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string facilidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Facilidad {
            get {
                return this.facilidadField;
            }
            set {
                this.facilidadField = value;
                this.RaisePropertyChanged("Facilidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSTerminalSoapChannel : AppWinAdministracion.WSTerminalRef.WSTerminalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTerminalSoapClient : System.ServiceModel.ClientBase<AppWinAdministracion.WSTerminalRef.WSTerminalSoap>, AppWinAdministracion.WSTerminalRef.WSTerminalSoap {
        
        public WSTerminalSoapClient() {
        }
        
        public WSTerminalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTerminalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTerminalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTerminalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppWinAdministracion.WSTerminalRef.Companias Buscar_Compania(string pNombre) {
            return base.Channel.Buscar_Compania(pNombre);
        }
        
        public void Alta_Compania(AppWinAdministracion.WSTerminalRef.Companias unaCompania) {
            base.Channel.Alta_Compania(unaCompania);
        }
        
        public void Eliminar_Compania(AppWinAdministracion.WSTerminalRef.Companias unaCompania) {
            base.Channel.Eliminar_Compania(unaCompania);
        }
        
        public void Modificar_Compania(AppWinAdministracion.WSTerminalRef.Companias unaCompania) {
            base.Channel.Modificar_Compania(unaCompania);
        }
        
        public AppWinAdministracion.WSTerminalRef.Companias[] Listar_Companias() {
            return base.Channel.Listar_Companias();
        }
        
        public AppWinAdministracion.WSTerminalRef.Companias[] Listar_Todos_Companias() {
            return base.Channel.Listar_Todos_Companias();
        }
        
        public AppWinAdministracion.WSTerminalRef.Terminales Buscar_Terminal(string pCodigo) {
            return base.Channel.Buscar_Terminal(pCodigo);
        }
        
        public void Alta_Terminal(AppWinAdministracion.WSTerminalRef.Terminales unaTerminal) {
            base.Channel.Alta_Terminal(unaTerminal);
        }
        
        public void Eliminar_Terminal(AppWinAdministracion.WSTerminalRef.Terminales unaTerminal) {
            base.Channel.Eliminar_Terminal(unaTerminal);
        }
        
        public void Modificar_Terminal(AppWinAdministracion.WSTerminalRef.Terminales unaTerminal) {
            base.Channel.Modificar_Terminal(unaTerminal);
        }
        
        public AppWinAdministracion.WSTerminalRef.Terminales[] Listar_Terminales() {
            return base.Channel.Listar_Terminales();
        }
        
        public AppWinAdministracion.WSTerminalRef.Terminales[] Listar_Todos_Terminales() {
            return base.Channel.Listar_Todos_Terminales();
        }
        
        public AppWinAdministracion.WSTerminalRef.Viajes Buscar_Viaje(int pCodigo) {
            return base.Channel.Buscar_Viaje(pCodigo);
        }
        
        public void Alta_Viaje(AppWinAdministracion.WSTerminalRef.Viajes unViaje) {
            base.Channel.Alta_Viaje(unViaje);
        }
        
        public void Eliminar_Viaje(AppWinAdministracion.WSTerminalRef.Viajes unViaje) {
            base.Channel.Eliminar_Viaje(unViaje);
        }
        
        public void Modificar_Viaje(AppWinAdministracion.WSTerminalRef.Viajes unViaje) {
            base.Channel.Modificar_Viaje(unViaje);
        }
        
        public AppWinAdministracion.WSTerminalRef.Viajes[] Listar_Viajes() {
            return base.Channel.Listar_Viajes();
        }
        
        public AppWinAdministracion.WSTerminalRef.Empleados Login(string pCed, string pPass) {
            return base.Channel.Login(pCed, pPass);
        }
        
        public AppWinAdministracion.WSTerminalRef.Empleados Buscar_Empleado(string pCedula) {
            return base.Channel.Buscar_Empleado(pCedula);
        }
        
        public AppWinAdministracion.WSTerminalRef.Empleados BuscarTodos_Empleado(string pCedula) {
            return base.Channel.BuscarTodos_Empleado(pCedula);
        }
        
        public void Alta_Empleado(AppWinAdministracion.WSTerminalRef.Empleados unEmpleado) {
            base.Channel.Alta_Empleado(unEmpleado);
        }
        
        public void Eliminar_Empleado(AppWinAdministracion.WSTerminalRef.Empleados unEmpleado) {
            base.Channel.Eliminar_Empleado(unEmpleado);
        }
        
        public void Modificar_Empleado(AppWinAdministracion.WSTerminalRef.Empleados unEmpleado) {
            base.Channel.Modificar_Empleado(unEmpleado);
        }
    }
}
