//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppWinAdministracion.WSTerminalRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSTerminalSoap", Namespace="http://tempuri.org/")]
    public partial class WSTerminal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Buscar_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Alta_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Modificar_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Eliminar_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_CompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_Todos_CompaniasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTerminal() {
            this.Url = global::AppWinAdministracion.Properties.Settings.Default.AppWinAdministracion_WSTerminalRef_WSTerminal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Buscar_CompaniaCompletedEventHandler Buscar_CompaniaCompleted;
        
        /// <remarks/>
        public event Alta_CompaniaCompletedEventHandler Alta_CompaniaCompleted;
        
        /// <remarks/>
        public event Modificar_CompaniaCompletedEventHandler Modificar_CompaniaCompleted;
        
        /// <remarks/>
        public event Eliminar_CompaniaCompletedEventHandler Eliminar_CompaniaCompleted;
        
        /// <remarks/>
        public event Listar_CompaniasCompletedEventHandler Listar_CompaniasCompleted;
        
        /// <remarks/>
        public event Listar_Todos_CompaniasCompletedEventHandler Listar_Todos_CompaniasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Buscar_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Companias Buscar_Compania(string pNombre) {
            object[] results = this.Invoke("Buscar_Compania", new object[] {
                        pNombre});
            return ((Companias)(results[0]));
        }
        
        /// <remarks/>
        public void Buscar_CompaniaAsync(string pNombre) {
            this.Buscar_CompaniaAsync(pNombre, null);
        }
        
        /// <remarks/>
        public void Buscar_CompaniaAsync(string pNombre, object userState) {
            if ((this.Buscar_CompaniaOperationCompleted == null)) {
                this.Buscar_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscar_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Buscar_Compania", new object[] {
                        pNombre}, this.Buscar_CompaniaOperationCompleted, userState);
        }
        
        private void OnBuscar_CompaniaOperationCompleted(object arg) {
            if ((this.Buscar_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Buscar_CompaniaCompleted(this, new Buscar_CompaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Alta_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Alta_Compania(Companias unaCompania) {
            this.Invoke("Alta_Compania", new object[] {
                        unaCompania});
        }
        
        /// <remarks/>
        public void Alta_CompaniaAsync(Companias unaCompania) {
            this.Alta_CompaniaAsync(unaCompania, null);
        }
        
        /// <remarks/>
        public void Alta_CompaniaAsync(Companias unaCompania, object userState) {
            if ((this.Alta_CompaniaOperationCompleted == null)) {
                this.Alta_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlta_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Alta_Compania", new object[] {
                        unaCompania}, this.Alta_CompaniaOperationCompleted, userState);
        }
        
        private void OnAlta_CompaniaOperationCompleted(object arg) {
            if ((this.Alta_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Alta_CompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modificar_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modificar_Compania(Companias unaCompania) {
            this.Invoke("Modificar_Compania", new object[] {
                        unaCompania});
        }
        
        /// <remarks/>
        public void Modificar_CompaniaAsync(Companias unaCompania) {
            this.Modificar_CompaniaAsync(unaCompania, null);
        }
        
        /// <remarks/>
        public void Modificar_CompaniaAsync(Companias unaCompania, object userState) {
            if ((this.Modificar_CompaniaOperationCompleted == null)) {
                this.Modificar_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificar_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Modificar_Compania", new object[] {
                        unaCompania}, this.Modificar_CompaniaOperationCompleted, userState);
        }
        
        private void OnModificar_CompaniaOperationCompleted(object arg) {
            if ((this.Modificar_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Modificar_CompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar_Compania(Companias unaCompania) {
            this.Invoke("Eliminar_Compania", new object[] {
                        unaCompania});
        }
        
        /// <remarks/>
        public void Eliminar_CompaniaAsync(Companias unaCompania) {
            this.Eliminar_CompaniaAsync(unaCompania, null);
        }
        
        /// <remarks/>
        public void Eliminar_CompaniaAsync(Companias unaCompania, object userState) {
            if ((this.Eliminar_CompaniaOperationCompleted == null)) {
                this.Eliminar_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminar_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Eliminar_Compania", new object[] {
                        unaCompania}, this.Eliminar_CompaniaOperationCompleted, userState);
        }
        
        private void OnEliminar_CompaniaOperationCompleted(object arg) {
            if ((this.Eliminar_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Eliminar_CompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Companias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Companias[] Listar_Companias() {
            object[] results = this.Invoke("Listar_Companias", new object[0]);
            return ((Companias[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_CompaniasAsync() {
            this.Listar_CompaniasAsync(null);
        }
        
        /// <remarks/>
        public void Listar_CompaniasAsync(object userState) {
            if ((this.Listar_CompaniasOperationCompleted == null)) {
                this.Listar_CompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_CompaniasOperationCompleted);
            }
            this.InvokeAsync("Listar_Companias", new object[0], this.Listar_CompaniasOperationCompleted, userState);
        }
        
        private void OnListar_CompaniasOperationCompleted(object arg) {
            if ((this.Listar_CompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_CompaniasCompleted(this, new Listar_CompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Todos_Companias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Companias[] Listar_Todos_Companias() {
            object[] results = this.Invoke("Listar_Todos_Companias", new object[0]);
            return ((Companias[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_Todos_CompaniasAsync() {
            this.Listar_Todos_CompaniasAsync(null);
        }
        
        /// <remarks/>
        public void Listar_Todos_CompaniasAsync(object userState) {
            if ((this.Listar_Todos_CompaniasOperationCompleted == null)) {
                this.Listar_Todos_CompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_Todos_CompaniasOperationCompleted);
            }
            this.InvokeAsync("Listar_Todos_Companias", new object[0], this.Listar_Todos_CompaniasOperationCompleted, userState);
        }
        
        private void OnListar_Todos_CompaniasOperationCompleted(object arg) {
            if ((this.Listar_Todos_CompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_Todos_CompaniasCompleted(this, new Listar_Todos_CompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Companias {
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Buscar_CompaniaCompletedEventHandler(object sender, Buscar_CompaniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Buscar_CompaniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Buscar_CompaniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Companias Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Companias)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Alta_CompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Modificar_CompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Eliminar_CompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_CompaniasCompletedEventHandler(object sender, Listar_CompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_CompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_CompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Companias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Companias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_Todos_CompaniasCompletedEventHandler(object sender, Listar_Todos_CompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_Todos_CompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_Todos_CompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Companias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Companias[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591