//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppWinAdministracion.WSTerminalRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSTerminalSoap", Namespace="http://tempuri.org/")]
    public partial class WSTerminal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Buscar_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Alta_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Eliminar_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Modificar_CompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_CompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_Todos_CompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback Buscar_TerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback Alta_TerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback Eliminar_TerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback Modificar_TerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_TerminalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_Todos_TerminalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Buscar_ViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Alta_ViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Eliminar_ViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Modificar_ViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Listar_ViajesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Buscar_EmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarTodos_EmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Alta_EmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Eliminar_EmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Modificar_EmpleadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTerminal() {
            this.Url = global::AppWinAdministracion.Properties.Settings.Default.AppWinAdministracion_WSTerminalRef_WSTerminal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Buscar_CompaniaCompletedEventHandler Buscar_CompaniaCompleted;
        
        /// <remarks/>
        public event Alta_CompaniaCompletedEventHandler Alta_CompaniaCompleted;
        
        /// <remarks/>
        public event Eliminar_CompaniaCompletedEventHandler Eliminar_CompaniaCompleted;
        
        /// <remarks/>
        public event Modificar_CompaniaCompletedEventHandler Modificar_CompaniaCompleted;
        
        /// <remarks/>
        public event Listar_CompaniasCompletedEventHandler Listar_CompaniasCompleted;
        
        /// <remarks/>
        public event Listar_Todos_CompaniasCompletedEventHandler Listar_Todos_CompaniasCompleted;
        
        /// <remarks/>
        public event Buscar_TerminalCompletedEventHandler Buscar_TerminalCompleted;
        
        /// <remarks/>
        public event Alta_TerminalCompletedEventHandler Alta_TerminalCompleted;
        
        /// <remarks/>
        public event Eliminar_TerminalCompletedEventHandler Eliminar_TerminalCompleted;
        
        /// <remarks/>
        public event Modificar_TerminalCompletedEventHandler Modificar_TerminalCompleted;
        
        /// <remarks/>
        public event Listar_TerminalesCompletedEventHandler Listar_TerminalesCompleted;
        
        /// <remarks/>
        public event Listar_Todos_TerminalesCompletedEventHandler Listar_Todos_TerminalesCompleted;
        
        /// <remarks/>
        public event Buscar_ViajeCompletedEventHandler Buscar_ViajeCompleted;
        
        /// <remarks/>
        public event Alta_ViajeCompletedEventHandler Alta_ViajeCompleted;
        
        /// <remarks/>
        public event Eliminar_ViajeCompletedEventHandler Eliminar_ViajeCompleted;
        
        /// <remarks/>
        public event Modificar_ViajeCompletedEventHandler Modificar_ViajeCompleted;
        
        /// <remarks/>
        public event Listar_ViajesCompletedEventHandler Listar_ViajesCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event Buscar_EmpleadoCompletedEventHandler Buscar_EmpleadoCompleted;
        
        /// <remarks/>
        public event BuscarTodos_EmpleadoCompletedEventHandler BuscarTodos_EmpleadoCompleted;
        
        /// <remarks/>
        public event Alta_EmpleadoCompletedEventHandler Alta_EmpleadoCompleted;
        
        /// <remarks/>
        public event Eliminar_EmpleadoCompletedEventHandler Eliminar_EmpleadoCompleted;
        
        /// <remarks/>
        public event Modificar_EmpleadoCompletedEventHandler Modificar_EmpleadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Buscar_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Companias Buscar_Compania(string pNombre) {
            object[] results = this.Invoke("Buscar_Compania", new object[] {
                        pNombre});
            return ((Companias)(results[0]));
        }
        
        /// <remarks/>
        public void Buscar_CompaniaAsync(string pNombre) {
            this.Buscar_CompaniaAsync(pNombre, null);
        }
        
        /// <remarks/>
        public void Buscar_CompaniaAsync(string pNombre, object userState) {
            if ((this.Buscar_CompaniaOperationCompleted == null)) {
                this.Buscar_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscar_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Buscar_Compania", new object[] {
                        pNombre}, this.Buscar_CompaniaOperationCompleted, userState);
        }
        
        private void OnBuscar_CompaniaOperationCompleted(object arg) {
            if ((this.Buscar_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Buscar_CompaniaCompleted(this, new Buscar_CompaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Alta_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Alta_Compania(Companias unaCompania) {
            this.Invoke("Alta_Compania", new object[] {
                        unaCompania});
        }
        
        /// <remarks/>
        public void Alta_CompaniaAsync(Companias unaCompania) {
            this.Alta_CompaniaAsync(unaCompania, null);
        }
        
        /// <remarks/>
        public void Alta_CompaniaAsync(Companias unaCompania, object userState) {
            if ((this.Alta_CompaniaOperationCompleted == null)) {
                this.Alta_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlta_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Alta_Compania", new object[] {
                        unaCompania}, this.Alta_CompaniaOperationCompleted, userState);
        }
        
        private void OnAlta_CompaniaOperationCompleted(object arg) {
            if ((this.Alta_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Alta_CompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar_Compania(Companias unaCompania) {
            this.Invoke("Eliminar_Compania", new object[] {
                        unaCompania});
        }
        
        /// <remarks/>
        public void Eliminar_CompaniaAsync(Companias unaCompania) {
            this.Eliminar_CompaniaAsync(unaCompania, null);
        }
        
        /// <remarks/>
        public void Eliminar_CompaniaAsync(Companias unaCompania, object userState) {
            if ((this.Eliminar_CompaniaOperationCompleted == null)) {
                this.Eliminar_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminar_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Eliminar_Compania", new object[] {
                        unaCompania}, this.Eliminar_CompaniaOperationCompleted, userState);
        }
        
        private void OnEliminar_CompaniaOperationCompleted(object arg) {
            if ((this.Eliminar_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Eliminar_CompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modificar_Compania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modificar_Compania(Companias unaCompania) {
            this.Invoke("Modificar_Compania", new object[] {
                        unaCompania});
        }
        
        /// <remarks/>
        public void Modificar_CompaniaAsync(Companias unaCompania) {
            this.Modificar_CompaniaAsync(unaCompania, null);
        }
        
        /// <remarks/>
        public void Modificar_CompaniaAsync(Companias unaCompania, object userState) {
            if ((this.Modificar_CompaniaOperationCompleted == null)) {
                this.Modificar_CompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificar_CompaniaOperationCompleted);
            }
            this.InvokeAsync("Modificar_Compania", new object[] {
                        unaCompania}, this.Modificar_CompaniaOperationCompleted, userState);
        }
        
        private void OnModificar_CompaniaOperationCompleted(object arg) {
            if ((this.Modificar_CompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Modificar_CompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Companias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Companias[] Listar_Companias() {
            object[] results = this.Invoke("Listar_Companias", new object[0]);
            return ((Companias[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_CompaniasAsync() {
            this.Listar_CompaniasAsync(null);
        }
        
        /// <remarks/>
        public void Listar_CompaniasAsync(object userState) {
            if ((this.Listar_CompaniasOperationCompleted == null)) {
                this.Listar_CompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_CompaniasOperationCompleted);
            }
            this.InvokeAsync("Listar_Companias", new object[0], this.Listar_CompaniasOperationCompleted, userState);
        }
        
        private void OnListar_CompaniasOperationCompleted(object arg) {
            if ((this.Listar_CompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_CompaniasCompleted(this, new Listar_CompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Todos_Companias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Companias[] Listar_Todos_Companias() {
            object[] results = this.Invoke("Listar_Todos_Companias", new object[0]);
            return ((Companias[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_Todos_CompaniasAsync() {
            this.Listar_Todos_CompaniasAsync(null);
        }
        
        /// <remarks/>
        public void Listar_Todos_CompaniasAsync(object userState) {
            if ((this.Listar_Todos_CompaniasOperationCompleted == null)) {
                this.Listar_Todos_CompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_Todos_CompaniasOperationCompleted);
            }
            this.InvokeAsync("Listar_Todos_Companias", new object[0], this.Listar_Todos_CompaniasOperationCompleted, userState);
        }
        
        private void OnListar_Todos_CompaniasOperationCompleted(object arg) {
            if ((this.Listar_Todos_CompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_Todos_CompaniasCompleted(this, new Listar_Todos_CompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Buscar_Terminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminales Buscar_Terminal(string pCodigo) {
            object[] results = this.Invoke("Buscar_Terminal", new object[] {
                        pCodigo});
            return ((Terminales)(results[0]));
        }
        
        /// <remarks/>
        public void Buscar_TerminalAsync(string pCodigo) {
            this.Buscar_TerminalAsync(pCodigo, null);
        }
        
        /// <remarks/>
        public void Buscar_TerminalAsync(string pCodigo, object userState) {
            if ((this.Buscar_TerminalOperationCompleted == null)) {
                this.Buscar_TerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscar_TerminalOperationCompleted);
            }
            this.InvokeAsync("Buscar_Terminal", new object[] {
                        pCodigo}, this.Buscar_TerminalOperationCompleted, userState);
        }
        
        private void OnBuscar_TerminalOperationCompleted(object arg) {
            if ((this.Buscar_TerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Buscar_TerminalCompleted(this, new Buscar_TerminalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Alta_Terminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Alta_Terminal(Terminales unaTerminal) {
            this.Invoke("Alta_Terminal", new object[] {
                        unaTerminal});
        }
        
        /// <remarks/>
        public void Alta_TerminalAsync(Terminales unaTerminal) {
            this.Alta_TerminalAsync(unaTerminal, null);
        }
        
        /// <remarks/>
        public void Alta_TerminalAsync(Terminales unaTerminal, object userState) {
            if ((this.Alta_TerminalOperationCompleted == null)) {
                this.Alta_TerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlta_TerminalOperationCompleted);
            }
            this.InvokeAsync("Alta_Terminal", new object[] {
                        unaTerminal}, this.Alta_TerminalOperationCompleted, userState);
        }
        
        private void OnAlta_TerminalOperationCompleted(object arg) {
            if ((this.Alta_TerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Alta_TerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar_Terminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar_Terminal(Terminales unaTerminal) {
            this.Invoke("Eliminar_Terminal", new object[] {
                        unaTerminal});
        }
        
        /// <remarks/>
        public void Eliminar_TerminalAsync(Terminales unaTerminal) {
            this.Eliminar_TerminalAsync(unaTerminal, null);
        }
        
        /// <remarks/>
        public void Eliminar_TerminalAsync(Terminales unaTerminal, object userState) {
            if ((this.Eliminar_TerminalOperationCompleted == null)) {
                this.Eliminar_TerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminar_TerminalOperationCompleted);
            }
            this.InvokeAsync("Eliminar_Terminal", new object[] {
                        unaTerminal}, this.Eliminar_TerminalOperationCompleted, userState);
        }
        
        private void OnEliminar_TerminalOperationCompleted(object arg) {
            if ((this.Eliminar_TerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Eliminar_TerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modificar_Terminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modificar_Terminal(Terminales unaTerminal) {
            this.Invoke("Modificar_Terminal", new object[] {
                        unaTerminal});
        }
        
        /// <remarks/>
        public void Modificar_TerminalAsync(Terminales unaTerminal) {
            this.Modificar_TerminalAsync(unaTerminal, null);
        }
        
        /// <remarks/>
        public void Modificar_TerminalAsync(Terminales unaTerminal, object userState) {
            if ((this.Modificar_TerminalOperationCompleted == null)) {
                this.Modificar_TerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificar_TerminalOperationCompleted);
            }
            this.InvokeAsync("Modificar_Terminal", new object[] {
                        unaTerminal}, this.Modificar_TerminalOperationCompleted, userState);
        }
        
        private void OnModificar_TerminalOperationCompleted(object arg) {
            if ((this.Modificar_TerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Modificar_TerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Terminales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminales[] Listar_Terminales() {
            object[] results = this.Invoke("Listar_Terminales", new object[0]);
            return ((Terminales[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_TerminalesAsync() {
            this.Listar_TerminalesAsync(null);
        }
        
        /// <remarks/>
        public void Listar_TerminalesAsync(object userState) {
            if ((this.Listar_TerminalesOperationCompleted == null)) {
                this.Listar_TerminalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_TerminalesOperationCompleted);
            }
            this.InvokeAsync("Listar_Terminales", new object[0], this.Listar_TerminalesOperationCompleted, userState);
        }
        
        private void OnListar_TerminalesOperationCompleted(object arg) {
            if ((this.Listar_TerminalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_TerminalesCompleted(this, new Listar_TerminalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Todos_Terminales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminales[] Listar_Todos_Terminales() {
            object[] results = this.Invoke("Listar_Todos_Terminales", new object[0]);
            return ((Terminales[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_Todos_TerminalesAsync() {
            this.Listar_Todos_TerminalesAsync(null);
        }
        
        /// <remarks/>
        public void Listar_Todos_TerminalesAsync(object userState) {
            if ((this.Listar_Todos_TerminalesOperationCompleted == null)) {
                this.Listar_Todos_TerminalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_Todos_TerminalesOperationCompleted);
            }
            this.InvokeAsync("Listar_Todos_Terminales", new object[0], this.Listar_Todos_TerminalesOperationCompleted, userState);
        }
        
        private void OnListar_Todos_TerminalesOperationCompleted(object arg) {
            if ((this.Listar_Todos_TerminalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_Todos_TerminalesCompleted(this, new Listar_Todos_TerminalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Buscar_Viaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viajes Buscar_Viaje(int pCodigo) {
            object[] results = this.Invoke("Buscar_Viaje", new object[] {
                        pCodigo});
            return ((Viajes)(results[0]));
        }
        
        /// <remarks/>
        public void Buscar_ViajeAsync(int pCodigo) {
            this.Buscar_ViajeAsync(pCodigo, null);
        }
        
        /// <remarks/>
        public void Buscar_ViajeAsync(int pCodigo, object userState) {
            if ((this.Buscar_ViajeOperationCompleted == null)) {
                this.Buscar_ViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscar_ViajeOperationCompleted);
            }
            this.InvokeAsync("Buscar_Viaje", new object[] {
                        pCodigo}, this.Buscar_ViajeOperationCompleted, userState);
        }
        
        private void OnBuscar_ViajeOperationCompleted(object arg) {
            if ((this.Buscar_ViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Buscar_ViajeCompleted(this, new Buscar_ViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Alta_Viaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Alta_Viaje(Viajes unViaje) {
            this.Invoke("Alta_Viaje", new object[] {
                        unViaje});
        }
        
        /// <remarks/>
        public void Alta_ViajeAsync(Viajes unViaje) {
            this.Alta_ViajeAsync(unViaje, null);
        }
        
        /// <remarks/>
        public void Alta_ViajeAsync(Viajes unViaje, object userState) {
            if ((this.Alta_ViajeOperationCompleted == null)) {
                this.Alta_ViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlta_ViajeOperationCompleted);
            }
            this.InvokeAsync("Alta_Viaje", new object[] {
                        unViaje}, this.Alta_ViajeOperationCompleted, userState);
        }
        
        private void OnAlta_ViajeOperationCompleted(object arg) {
            if ((this.Alta_ViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Alta_ViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar_Viaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar_Viaje(Viajes unViaje) {
            this.Invoke("Eliminar_Viaje", new object[] {
                        unViaje});
        }
        
        /// <remarks/>
        public void Eliminar_ViajeAsync(Viajes unViaje) {
            this.Eliminar_ViajeAsync(unViaje, null);
        }
        
        /// <remarks/>
        public void Eliminar_ViajeAsync(Viajes unViaje, object userState) {
            if ((this.Eliminar_ViajeOperationCompleted == null)) {
                this.Eliminar_ViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminar_ViajeOperationCompleted);
            }
            this.InvokeAsync("Eliminar_Viaje", new object[] {
                        unViaje}, this.Eliminar_ViajeOperationCompleted, userState);
        }
        
        private void OnEliminar_ViajeOperationCompleted(object arg) {
            if ((this.Eliminar_ViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Eliminar_ViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modificar_Viaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modificar_Viaje(Viajes unViaje) {
            this.Invoke("Modificar_Viaje", new object[] {
                        unViaje});
        }
        
        /// <remarks/>
        public void Modificar_ViajeAsync(Viajes unViaje) {
            this.Modificar_ViajeAsync(unViaje, null);
        }
        
        /// <remarks/>
        public void Modificar_ViajeAsync(Viajes unViaje, object userState) {
            if ((this.Modificar_ViajeOperationCompleted == null)) {
                this.Modificar_ViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificar_ViajeOperationCompleted);
            }
            this.InvokeAsync("Modificar_Viaje", new object[] {
                        unViaje}, this.Modificar_ViajeOperationCompleted, userState);
        }
        
        private void OnModificar_ViajeOperationCompleted(object arg) {
            if ((this.Modificar_ViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Modificar_ViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar_Viajes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viajes[] Listar_Viajes() {
            object[] results = this.Invoke("Listar_Viajes", new object[0]);
            return ((Viajes[])(results[0]));
        }
        
        /// <remarks/>
        public void Listar_ViajesAsync() {
            this.Listar_ViajesAsync(null);
        }
        
        /// <remarks/>
        public void Listar_ViajesAsync(object userState) {
            if ((this.Listar_ViajesOperationCompleted == null)) {
                this.Listar_ViajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListar_ViajesOperationCompleted);
            }
            this.InvokeAsync("Listar_Viajes", new object[0], this.Listar_ViajesOperationCompleted, userState);
        }
        
        private void OnListar_ViajesOperationCompleted(object arg) {
            if ((this.Listar_ViajesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Listar_ViajesCompleted(this, new Listar_ViajesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleados Login(string pCed, string pPass) {
            object[] results = this.Invoke("Login", new object[] {
                        pCed,
                        pPass});
            return ((Empleados)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string pCed, string pPass) {
            this.LoginAsync(pCed, pPass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string pCed, string pPass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        pCed,
                        pPass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Buscar_Empleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleados Buscar_Empleado(string pCedula) {
            object[] results = this.Invoke("Buscar_Empleado", new object[] {
                        pCedula});
            return ((Empleados)(results[0]));
        }
        
        /// <remarks/>
        public void Buscar_EmpleadoAsync(string pCedula) {
            this.Buscar_EmpleadoAsync(pCedula, null);
        }
        
        /// <remarks/>
        public void Buscar_EmpleadoAsync(string pCedula, object userState) {
            if ((this.Buscar_EmpleadoOperationCompleted == null)) {
                this.Buscar_EmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscar_EmpleadoOperationCompleted);
            }
            this.InvokeAsync("Buscar_Empleado", new object[] {
                        pCedula}, this.Buscar_EmpleadoOperationCompleted, userState);
        }
        
        private void OnBuscar_EmpleadoOperationCompleted(object arg) {
            if ((this.Buscar_EmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Buscar_EmpleadoCompleted(this, new Buscar_EmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarTodos_Empleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleados BuscarTodos_Empleado(string pCedula) {
            object[] results = this.Invoke("BuscarTodos_Empleado", new object[] {
                        pCedula});
            return ((Empleados)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarTodos_EmpleadoAsync(string pCedula) {
            this.BuscarTodos_EmpleadoAsync(pCedula, null);
        }
        
        /// <remarks/>
        public void BuscarTodos_EmpleadoAsync(string pCedula, object userState) {
            if ((this.BuscarTodos_EmpleadoOperationCompleted == null)) {
                this.BuscarTodos_EmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarTodos_EmpleadoOperationCompleted);
            }
            this.InvokeAsync("BuscarTodos_Empleado", new object[] {
                        pCedula}, this.BuscarTodos_EmpleadoOperationCompleted, userState);
        }
        
        private void OnBuscarTodos_EmpleadoOperationCompleted(object arg) {
            if ((this.BuscarTodos_EmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarTodos_EmpleadoCompleted(this, new BuscarTodos_EmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Alta_Empleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Alta_Empleado(Empleados unEmpleado) {
            this.Invoke("Alta_Empleado", new object[] {
                        unEmpleado});
        }
        
        /// <remarks/>
        public void Alta_EmpleadoAsync(Empleados unEmpleado) {
            this.Alta_EmpleadoAsync(unEmpleado, null);
        }
        
        /// <remarks/>
        public void Alta_EmpleadoAsync(Empleados unEmpleado, object userState) {
            if ((this.Alta_EmpleadoOperationCompleted == null)) {
                this.Alta_EmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlta_EmpleadoOperationCompleted);
            }
            this.InvokeAsync("Alta_Empleado", new object[] {
                        unEmpleado}, this.Alta_EmpleadoOperationCompleted, userState);
        }
        
        private void OnAlta_EmpleadoOperationCompleted(object arg) {
            if ((this.Alta_EmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Alta_EmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar_Empleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar_Empleado(Empleados unEmpleado) {
            this.Invoke("Eliminar_Empleado", new object[] {
                        unEmpleado});
        }
        
        /// <remarks/>
        public void Eliminar_EmpleadoAsync(Empleados unEmpleado) {
            this.Eliminar_EmpleadoAsync(unEmpleado, null);
        }
        
        /// <remarks/>
        public void Eliminar_EmpleadoAsync(Empleados unEmpleado, object userState) {
            if ((this.Eliminar_EmpleadoOperationCompleted == null)) {
                this.Eliminar_EmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminar_EmpleadoOperationCompleted);
            }
            this.InvokeAsync("Eliminar_Empleado", new object[] {
                        unEmpleado}, this.Eliminar_EmpleadoOperationCompleted, userState);
        }
        
        private void OnEliminar_EmpleadoOperationCompleted(object arg) {
            if ((this.Eliminar_EmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Eliminar_EmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modificar_Empleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modificar_Empleado(Empleados unEmpleado) {
            this.Invoke("Modificar_Empleado", new object[] {
                        unEmpleado});
        }
        
        /// <remarks/>
        public void Modificar_EmpleadoAsync(Empleados unEmpleado) {
            this.Modificar_EmpleadoAsync(unEmpleado, null);
        }
        
        /// <remarks/>
        public void Modificar_EmpleadoAsync(Empleados unEmpleado, object userState) {
            if ((this.Modificar_EmpleadoOperationCompleted == null)) {
                this.Modificar_EmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificar_EmpleadoOperationCompleted);
            }
            this.InvokeAsync("Modificar_Empleado", new object[] {
                        unEmpleado}, this.Modificar_EmpleadoOperationCompleted, userState);
        }
        
        private void OnModificar_EmpleadoOperationCompleted(object arg) {
            if ((this.Modificar_EmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Modificar_EmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Companias {
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleados {
        
        private string cedulaField;
        
        private string passField;
        
        private string nombreField;
        
        /// <remarks/>
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Viajes {
        
        private int numeroField;
        
        private Companias companiaField;
        
        private Terminales terminalField;
        
        private System.DateTime fecha_partidaField;
        
        private System.DateTime fecha_arriboField;
        
        private int asientosField;
        
        private Empleados empleadoField;
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public Companias Compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
            }
        }
        
        /// <remarks/>
        public Terminales Terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha_partida {
            get {
                return this.fecha_partidaField;
            }
            set {
                this.fecha_partidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha_arribo {
            get {
                return this.fecha_arriboField;
            }
            set {
                this.fecha_arriboField = value;
            }
        }
        
        /// <remarks/>
        public int Asientos {
            get {
                return this.asientosField;
            }
            set {
                this.asientosField = value;
            }
        }
        
        /// <remarks/>
        public Empleados Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Terminales {
        
        private string codigoField;
        
        private string ciudadField;
        
        private string paisField;
        
        private Facilidades[] listaFacilidadesField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public Facilidades[] ListaFacilidades {
            get {
                return this.listaFacilidadesField;
            }
            set {
                this.listaFacilidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Facilidades {
        
        private string facilidadField;
        
        /// <remarks/>
        public string Facilidad {
            get {
                return this.facilidadField;
            }
            set {
                this.facilidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Buscar_CompaniaCompletedEventHandler(object sender, Buscar_CompaniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Buscar_CompaniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Buscar_CompaniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Companias Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Companias)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Alta_CompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Eliminar_CompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Modificar_CompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_CompaniasCompletedEventHandler(object sender, Listar_CompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_CompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_CompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Companias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Companias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_Todos_CompaniasCompletedEventHandler(object sender, Listar_Todos_CompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_Todos_CompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_Todos_CompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Companias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Companias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Buscar_TerminalCompletedEventHandler(object sender, Buscar_TerminalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Buscar_TerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Buscar_TerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminales Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminales)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Alta_TerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Eliminar_TerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Modificar_TerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_TerminalesCompletedEventHandler(object sender, Listar_TerminalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_TerminalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_TerminalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminales[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_Todos_TerminalesCompletedEventHandler(object sender, Listar_Todos_TerminalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_Todos_TerminalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_Todos_TerminalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminales[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Buscar_ViajeCompletedEventHandler(object sender, Buscar_ViajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Buscar_ViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Buscar_ViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viajes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viajes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Alta_ViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Eliminar_ViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Modificar_ViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Listar_ViajesCompletedEventHandler(object sender, Listar_ViajesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Listar_ViajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Listar_ViajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viajes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viajes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleados Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleados)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Buscar_EmpleadoCompletedEventHandler(object sender, Buscar_EmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Buscar_EmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Buscar_EmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleados Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleados)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarTodos_EmpleadoCompletedEventHandler(object sender, BuscarTodos_EmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarTodos_EmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarTodos_EmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleados Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleados)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Alta_EmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Eliminar_EmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Modificar_EmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591