//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWinAdministracion.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Companias", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Companias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pNombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar_Compania", ReplyAction="*")]
        AppWinAdministracion.WS.Buscar_CompaniaResponse Buscar_Compania(AppWinAdministracion.WS.Buscar_CompaniaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento unaCompania del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Compania", ReplyAction="*")]
        AppWinAdministracion.WS.Alta_CompaniaResponse Alta_Compania(AppWinAdministracion.WS.Alta_CompaniaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento unaCompania del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar_Compania", ReplyAction="*")]
        AppWinAdministracion.WS.Modificar_CompaniaResponse Modificar_Compania(AppWinAdministracion.WS.Modificar_CompaniaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento unaCompania del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Compania", ReplyAction="*")]
        AppWinAdministracion.WS.Eliminar_CompaniaResponse Eliminar_Compania(AppWinAdministracion.WS.Eliminar_CompaniaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Listar_CompaniasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Companias", ReplyAction="*")]
        AppWinAdministracion.WS.Listar_CompaniasResponse Listar_Companias(AppWinAdministracion.WS.Listar_CompaniasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Listar_Todos_CompaniasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Todos_Companias", ReplyAction="*")]
        AppWinAdministracion.WS.Listar_Todos_CompaniasResponse Listar_Todos_Companias(AppWinAdministracion.WS.Listar_Todos_CompaniasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Buscar_CompaniaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar_Compania", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Buscar_CompaniaRequestBody Body;
        
        public Buscar_CompaniaRequest() {
        }
        
        public Buscar_CompaniaRequest(AppWinAdministracion.WS.Buscar_CompaniaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Buscar_CompaniaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pNombre;
        
        public Buscar_CompaniaRequestBody() {
        }
        
        public Buscar_CompaniaRequestBody(string pNombre) {
            this.pNombre = pNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Buscar_CompaniaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar_CompaniaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Buscar_CompaniaResponseBody Body;
        
        public Buscar_CompaniaResponse() {
        }
        
        public Buscar_CompaniaResponse(AppWinAdministracion.WS.Buscar_CompaniaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Buscar_CompaniaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWinAdministracion.WS.Companias Buscar_CompaniaResult;
        
        public Buscar_CompaniaResponseBody() {
        }
        
        public Buscar_CompaniaResponseBody(AppWinAdministracion.WS.Companias Buscar_CompaniaResult) {
            this.Buscar_CompaniaResult = Buscar_CompaniaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_CompaniaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alta_Compania", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Alta_CompaniaRequestBody Body;
        
        public Alta_CompaniaRequest() {
        }
        
        public Alta_CompaniaRequest(AppWinAdministracion.WS.Alta_CompaniaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Alta_CompaniaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWinAdministracion.WS.Companias unaCompania;
        
        public Alta_CompaniaRequestBody() {
        }
        
        public Alta_CompaniaRequestBody(AppWinAdministracion.WS.Companias unaCompania) {
            this.unaCompania = unaCompania;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_CompaniaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alta_CompaniaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Alta_CompaniaResponseBody Body;
        
        public Alta_CompaniaResponse() {
        }
        
        public Alta_CompaniaResponse(AppWinAdministracion.WS.Alta_CompaniaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Alta_CompaniaResponseBody {
        
        public Alta_CompaniaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Modificar_CompaniaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar_Compania", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Modificar_CompaniaRequestBody Body;
        
        public Modificar_CompaniaRequest() {
        }
        
        public Modificar_CompaniaRequest(AppWinAdministracion.WS.Modificar_CompaniaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Modificar_CompaniaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWinAdministracion.WS.Companias unaCompania;
        
        public Modificar_CompaniaRequestBody() {
        }
        
        public Modificar_CompaniaRequestBody(AppWinAdministracion.WS.Companias unaCompania) {
            this.unaCompania = unaCompania;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Modificar_CompaniaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar_CompaniaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Modificar_CompaniaResponseBody Body;
        
        public Modificar_CompaniaResponse() {
        }
        
        public Modificar_CompaniaResponse(AppWinAdministracion.WS.Modificar_CompaniaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Modificar_CompaniaResponseBody {
        
        public Modificar_CompaniaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_CompaniaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_Compania", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Eliminar_CompaniaRequestBody Body;
        
        public Eliminar_CompaniaRequest() {
        }
        
        public Eliminar_CompaniaRequest(AppWinAdministracion.WS.Eliminar_CompaniaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_CompaniaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWinAdministracion.WS.Companias unaCompania;
        
        public Eliminar_CompaniaRequestBody() {
        }
        
        public Eliminar_CompaniaRequestBody(AppWinAdministracion.WS.Companias unaCompania) {
            this.unaCompania = unaCompania;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_CompaniaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_CompaniaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Eliminar_CompaniaResponseBody Body;
        
        public Eliminar_CompaniaResponse() {
        }
        
        public Eliminar_CompaniaResponse(AppWinAdministracion.WS.Eliminar_CompaniaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Eliminar_CompaniaResponseBody {
        
        public Eliminar_CompaniaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Listar_CompaniasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar_Companias", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Listar_CompaniasRequestBody Body;
        
        public Listar_CompaniasRequest() {
        }
        
        public Listar_CompaniasRequest(AppWinAdministracion.WS.Listar_CompaniasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Listar_CompaniasRequestBody {
        
        public Listar_CompaniasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Listar_CompaniasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar_CompaniasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Listar_CompaniasResponseBody Body;
        
        public Listar_CompaniasResponse() {
        }
        
        public Listar_CompaniasResponse(AppWinAdministracion.WS.Listar_CompaniasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Listar_CompaniasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWinAdministracion.WS.Companias[] Listar_CompaniasResult;
        
        public Listar_CompaniasResponseBody() {
        }
        
        public Listar_CompaniasResponseBody(AppWinAdministracion.WS.Companias[] Listar_CompaniasResult) {
            this.Listar_CompaniasResult = Listar_CompaniasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Listar_Todos_CompaniasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar_Todos_Companias", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Listar_Todos_CompaniasRequestBody Body;
        
        public Listar_Todos_CompaniasRequest() {
        }
        
        public Listar_Todos_CompaniasRequest(AppWinAdministracion.WS.Listar_Todos_CompaniasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Listar_Todos_CompaniasRequestBody {
        
        public Listar_Todos_CompaniasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Listar_Todos_CompaniasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar_Todos_CompaniasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWinAdministracion.WS.Listar_Todos_CompaniasResponseBody Body;
        
        public Listar_Todos_CompaniasResponse() {
        }
        
        public Listar_Todos_CompaniasResponse(AppWinAdministracion.WS.Listar_Todos_CompaniasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Listar_Todos_CompaniasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWinAdministracion.WS.Companias[] Listar_Todos_CompaniasResult;
        
        public Listar_Todos_CompaniasResponseBody() {
        }
        
        public Listar_Todos_CompaniasResponseBody(AppWinAdministracion.WS.Companias[] Listar_Todos_CompaniasResult) {
            this.Listar_Todos_CompaniasResult = Listar_Todos_CompaniasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : AppWinAdministracion.WS.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<AppWinAdministracion.WS.MyWebServiceSoap>, AppWinAdministracion.WS.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWinAdministracion.WS.Buscar_CompaniaResponse AppWinAdministracion.WS.MyWebServiceSoap.Buscar_Compania(AppWinAdministracion.WS.Buscar_CompaniaRequest request) {
            return base.Channel.Buscar_Compania(request);
        }
        
        public AppWinAdministracion.WS.Companias Buscar_Compania(string pNombre) {
            AppWinAdministracion.WS.Buscar_CompaniaRequest inValue = new AppWinAdministracion.WS.Buscar_CompaniaRequest();
            inValue.Body = new AppWinAdministracion.WS.Buscar_CompaniaRequestBody();
            inValue.Body.pNombre = pNombre;
            AppWinAdministracion.WS.Buscar_CompaniaResponse retVal = ((AppWinAdministracion.WS.MyWebServiceSoap)(this)).Buscar_Compania(inValue);
            return retVal.Body.Buscar_CompaniaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWinAdministracion.WS.Alta_CompaniaResponse AppWinAdministracion.WS.MyWebServiceSoap.Alta_Compania(AppWinAdministracion.WS.Alta_CompaniaRequest request) {
            return base.Channel.Alta_Compania(request);
        }
        
        public void Alta_Compania(AppWinAdministracion.WS.Companias unaCompania) {
            AppWinAdministracion.WS.Alta_CompaniaRequest inValue = new AppWinAdministracion.WS.Alta_CompaniaRequest();
            inValue.Body = new AppWinAdministracion.WS.Alta_CompaniaRequestBody();
            inValue.Body.unaCompania = unaCompania;
            AppWinAdministracion.WS.Alta_CompaniaResponse retVal = ((AppWinAdministracion.WS.MyWebServiceSoap)(this)).Alta_Compania(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWinAdministracion.WS.Modificar_CompaniaResponse AppWinAdministracion.WS.MyWebServiceSoap.Modificar_Compania(AppWinAdministracion.WS.Modificar_CompaniaRequest request) {
            return base.Channel.Modificar_Compania(request);
        }
        
        public void Modificar_Compania(AppWinAdministracion.WS.Companias unaCompania) {
            AppWinAdministracion.WS.Modificar_CompaniaRequest inValue = new AppWinAdministracion.WS.Modificar_CompaniaRequest();
            inValue.Body = new AppWinAdministracion.WS.Modificar_CompaniaRequestBody();
            inValue.Body.unaCompania = unaCompania;
            AppWinAdministracion.WS.Modificar_CompaniaResponse retVal = ((AppWinAdministracion.WS.MyWebServiceSoap)(this)).Modificar_Compania(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWinAdministracion.WS.Eliminar_CompaniaResponse AppWinAdministracion.WS.MyWebServiceSoap.Eliminar_Compania(AppWinAdministracion.WS.Eliminar_CompaniaRequest request) {
            return base.Channel.Eliminar_Compania(request);
        }
        
        public void Eliminar_Compania(AppWinAdministracion.WS.Companias unaCompania) {
            AppWinAdministracion.WS.Eliminar_CompaniaRequest inValue = new AppWinAdministracion.WS.Eliminar_CompaniaRequest();
            inValue.Body = new AppWinAdministracion.WS.Eliminar_CompaniaRequestBody();
            inValue.Body.unaCompania = unaCompania;
            AppWinAdministracion.WS.Eliminar_CompaniaResponse retVal = ((AppWinAdministracion.WS.MyWebServiceSoap)(this)).Eliminar_Compania(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWinAdministracion.WS.Listar_CompaniasResponse AppWinAdministracion.WS.MyWebServiceSoap.Listar_Companias(AppWinAdministracion.WS.Listar_CompaniasRequest request) {
            return base.Channel.Listar_Companias(request);
        }
        
        public AppWinAdministracion.WS.Companias[] Listar_Companias() {
            AppWinAdministracion.WS.Listar_CompaniasRequest inValue = new AppWinAdministracion.WS.Listar_CompaniasRequest();
            inValue.Body = new AppWinAdministracion.WS.Listar_CompaniasRequestBody();
            AppWinAdministracion.WS.Listar_CompaniasResponse retVal = ((AppWinAdministracion.WS.MyWebServiceSoap)(this)).Listar_Companias(inValue);
            return retVal.Body.Listar_CompaniasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWinAdministracion.WS.Listar_Todos_CompaniasResponse AppWinAdministracion.WS.MyWebServiceSoap.Listar_Todos_Companias(AppWinAdministracion.WS.Listar_Todos_CompaniasRequest request) {
            return base.Channel.Listar_Todos_Companias(request);
        }
        
        public AppWinAdministracion.WS.Companias[] Listar_Todos_Companias() {
            AppWinAdministracion.WS.Listar_Todos_CompaniasRequest inValue = new AppWinAdministracion.WS.Listar_Todos_CompaniasRequest();
            inValue.Body = new AppWinAdministracion.WS.Listar_Todos_CompaniasRequestBody();
            AppWinAdministracion.WS.Listar_Todos_CompaniasResponse retVal = ((AppWinAdministracion.WS.MyWebServiceSoap)(this)).Listar_Todos_Companias(inValue);
            return retVal.Body.Listar_Todos_CompaniasResult;
        }
    }
}
